-d C:\Users\Ev\Documents\dual_port_ram\impl\gwsynthesis\dual_port_ram.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\Ev\Documents\dual_port_ram\src\dual_port_ram.cst
-cfg C:\Users\Ev\Documents\dual_port_ram\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
